version: "3.7"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        SA_PASSWORD: 'Admin#123'
        ACCEPT_EULA: 'Y'
    volumes:
        - sqldata:/var/opt/mssql
    ports: 
        - "1433:1433"

volumes:
  sqldata:
